name: unicornlauncher
description: An aesthetically-pleasing launcher for unicorns.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  cupertino_icons: ^1.0.2
  device_apps: ^1.0.9
  loading_animations: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: Garamond
      fonts:
        - asset: assets/Garamond.ttf
