import 'package:flutter/material.dart';
import 'package:dio/dio.dart';

String appTitle = 'Unicorn Launcher';
Dio dio = Dio();
String quotesAPI = 'https://blckunicorn.art/assets/unicornlauncher/api/quotes.json';
String wallpapersAPI = 'https://blckunicorn.art/assets/unicornlauncher/api/wallpapers.json';
String defaultImage = 'https://raw.githubusercontent.com/iamtheblackunicorn/iamtheblackunicorn.github.io/main/assets/unicornlauncher/images/wallpaperSeven.jpg';
Color accentColor = Color(0xFFFFFFFF);
Color mainColor = Color(0xFF000000);
double headingFontSize = 40;
double stdPadding = 7;
double stdFontSize = 20;
double stdRounding = 25;
double stdIconSize = 25;
double headingSpacing = 30;
double stdSpacing = 20;
double cardPadding = 10;
double stdWidth = 200;
double postHeadingFontSize = 25;
double extraRounding = 25;
double headerImageDimensions = 200;
double miscScreenSpacing = 170;
double miscScreenIconSize = 150;
String quoteFont = 'Garamond';
String dateFont = 'Ostrich';
Color quoteColor = Color(0xFF000000);
double quoteSize =20;
double dateSize = 40;
double appNameSize = 20;
double appPadding = 15;
