import 'package:flutter/material.dart';

String appVersion = '1.0.0';
String imageLink = 'https://iamtheblackunicorn.github.io/assets/images/posts/postEight.jpg';
Color accentColor = Color(0xFFDF0045);
Color mainColor = Color(0xFF000000);
double headingFontSize = 40;
double stdPadding = 7;
double stdFontSize = 20;
double stdRounding = 25;
double stdIconSize = 25;
double headingSpacing = 30;
double stdSpacing = 20;
double cardPadding = 10;
double stdWidth = 200;
double postHeadingFontSize = 25;
double extraRounding = 25;
double headerImageDimensions = 200;
double miscScreenSpacing = 170;
double miscScreenIconSize = 150;
